### PR TITLE
ByteArrayValueHandler should accept primitive byte array. Usage java functional interfaces

### PR DESCRIPTION
**Pull request by kowalczm**
For optimization it would be good to add/refactor ByteArrayValueHandler for primitive byte arrays

### CODE REVIEW

**Comment by bytefish** [comment]
Thanks! Do you think existing code will continue to work... I mean, will Java Auto Box these values? I wonder if it is a breaking change to the handler and may affect people using it.

**Comment by kowalczm** [comment]
Hi,
Yes, it breaks contract but it is hard to imagine that some 'low level' development is relying on Byte objects instead of byte arrays. We could add this change as a new class but it would be good to register it in provider as a replacement of existing? In our case we had to 'wrap' all byte[] to Byte[]

**Comment by kowalczm** [comment]
I have added additional changes to use standard java interfaces

**Comment by kowalczm** [comment]
Ok, looking forward release :)

**Comment by bytefish** [comment]
Yes. Your second commit changed a lot. Are these urgent changes, like you cannot proceed without them? I would rather make such changes with a new major revision to indicate breaking changes in the API, like adding generics to the mapping. I will think about what's best, but it can take until the weekend.

**Comment by kowalczm** [comment]
@bytefish, no problem. It's up to you

**Comment by bytefish** [comment]
I am not fixing the Unit Tests, Increase to Version 3.0 and then Release it to Maven! 👍

**Comment by bytefish** [comment]
All Tests passed, Releasing it to Maven! 👍

**Comment by kowalczm** [comment]
Thank you for merge and release

**Pull request merged**
