### PR TITLE
Update driver

### PR DESCRIPTION
**Pull request by paplorinc**
Note https://www.postgresql.org/about/news/2000, especially https://github.com/pgjdbc/pgjdbc/pull/1639

### CODE REVIEW

**Comment by bytefish** [comment]
@paplorinc Thanks for your Pull Request! I am short on time today, so I leave this open and assign myself as a reminder to do it tommorow. I will also upload the new package to the Maven Central repositories then.

**Comment by bytefish** [comment]
All tests work. I am preparing the release and update everything as soon as it is uploaded to Maven.

**Comment by bytefish** [comment]
@paplorinc I have released 3.5 to Maven Central repositories. Thanks for your contribution! 👍

**Comment by paplorinc** [comment]
Thanks.

**Pull request merged**
