### PR TITLE
Added buffer size for used BufferedOutputStream

### PR DESCRIPTION
**Pull request by kowalczm**
Upgraded postgrsql jdbc driver to 42.2.2

### CODE REVIEW

**Comment by bytefish** [comment]
Thanks for the Pull Request! 🙏 I will need some time to review it. Do you have any figures on performance improvements?

**Comment by kowalczm** [comment]
I have played with 'IntegrationTest.java' and see that having configrable buffer size we can control how many calls are done for Postgres Db and see significant performance improvment when sending data. So for larger buffer size than default in PGCopyOutputStream (65536) we are deacresing calls to db. Additionality byte array copying from BufferedOutputStream to PGCopyOutputStream is removed when BufferedOutputStream buffer size is less that PGCopyOutputStream buffer size.

**Comment by bytefish** [comment]
Sorry for my very late reply. I am not reviewing it.

**Comment by bytefish** [comment]
Could you explain, why you are setting the Buffer Size to ``1`` for the ``PGCopyOutputStream``? Maybe I am not understanding Java good enough.

```java
new DataOutputStream(new BufferedOutputStream(new PGCopyOutputStream(copyIn, 1), bufferSize));
```

**Comment by bytefish** [comment]
@kowalczm Ah I get it. The ``PgCopyOutputStream`` has some range checks and if the buffer size is 1, then it will always write as soon as the ``BufferedOutputStream`` flushes. Nice one. 👍

**Comment by bytefish** [comment]
Yes, I have read through the Postgres JDBC Driver code. I see two options here... 

1. Remove the ``BufferedOutputStream``, because the ``PGCopyOutputStream`` is already buffered. 
2. Set the ``PGCopyOutputStream`` buffer size to 1 and use a ``BufferedOutputStream``. 

If one uses the 2. approach, then at the end of the day the ``PGCopyOutputStream`` simply dispatches writes through to the ``CopyIn``. This will indeed stop any Memory Copying Operations introduced by me due to a small Buffer Size in the ``BufferedOutputStream``.

I have opted to go for the 1. option, that you have used as well. If it mysteriously breaks, then we will use the 2. approach. The ``PgBulkInsert`` class now accepts a ``IConfiguration`` to adjust the Buffer Size.

**Comment by bytefish** [comment]
Released Version 2.1 with a Configurable Buffer Size. Thanks! 👍

**Pull request closed without merging**
