### PR TITLE
Pull for following three resean: 

### PR DESCRIPTION
**Pull request by tangyibo**
1、modify SimpleRow.java : java basic data type to wrapper type for maybe the null value;
2、modify SimpleRow.java : add a function called setDouble(int ordinal, Double value);
3、modify SimpleRow.java : handle text string for invalid utf8 character

### CODE REVIEW

**Comment by bytefish** [comment]
Give me a moment to check the code!

**Comment by bytefish** [comment]
You are totally right, the API didn't account for ``null`` values!

As for ``StringUtils.escapeString``. I would opt for a way, so you can choose to either replace ``0x00`` or not. I think this would be more explicit. Maybe a flag? Or one adds a method ``setTextEscaped(...)``, that would be best I think.  

The reason is: Right now the escaping is hardcoded and that makes it hard to work around it. Maybe some external system already sanitized the Input and you don't want to redo the work.

We could also use a Regexp for this I think like:

```_stringValue.replaceAll("\u0000", "")```

**Comment by tangyibo** [comment]
Hello @bytefish , I test it will make error by PostgreSQL server(maybe in postgresql driver) when text string contais invalid utf8 character , You can make some test for it.

**Comment by bytefish** [comment]
@tangyibo Maybe you can give me write access to your branch, so we can work on it together: 

* https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by bytefish** [comment]
Great! I am happy with this. Let me know, when you are ready so I can merge it. 😎

**Comment by tangyibo** [comment]
@bytefish  I have done like what you said, You can test please!

**Comment by bytefish** [comment]
I have modified the API a little, to keep the function names clean. Instead of having two functions for Null Character Handling / Non-Null Character Handling you can pass your own handling into the ``SimpleRowWriter`` or use the one you implemented.

See the README at:

* https://github.com/bytefish/PgBulkInsert#handling-null-characters-or-invalid-byte-sequence-for-encoding-utf8-0x00

I hope you like it! 

I have uploaded the 3.8 to the Central Maven Repositories, so it should be available soon.

**Pull request merged**
